"""missionTime_string

Revision ID: 09c05f993690
Revises: 0011
Create Date: 2026-05-17 22:35:07.726855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '09c05f993690'
down_revision: Union[str, None] = '0011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_audit_logs_action'), table_name='api_audit_logs')
    op.drop_index(op.f('ix_api_audit_logs_createdAt'), table_name='api_audit_logs')
    op.alter_column('api_mission_admin_panels', 'missionTime',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_constraint(op.f('api_mission_admin_panels_mission_code_key'), 'api_mission_admin_panels', type_='unique')
    op.drop_index(op.f('ix_api_mission_admin_panels_mission_code'), table_name='api_mission_admin_panels')
    op.create_index(op.f('ix_api_mission_admin_panels_missionCode'), 'api_mission_admin_panels', ['missionCode'], unique=True)
    op.drop_index(op.f('ix_api_token_store_user_id'), table_name='api_token_store')
    op.create_index(op.f('ix_api_token_store_userId'), 'api_token_store', ['userId'], unique=False)
    op.drop_constraint(op.f('uq_api_user_profiles_userId'), 'api_user_profiles', type_='unique')
    op.drop_index(op.f('ix_api_user_profiles_userId'), table_name='api_user_profiles')
    op.create_index(op.f('ix_api_user_profiles_userId'), 'api_user_profiles', ['userId'], unique=True)
    op.drop_constraint(op.f('api_van_requests_request_id_key'), 'api_van_requests', type_='unique')
    op.drop_index(op.f('ix_api_van_requests_request_id'), table_name='api_van_requests')
    op.create_index(op.f('ix_api_van_requests_requestId'), 'api_van_requests', ['requestId'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_van_requests_requestId'), table_name='api_van_requests')
    op.create_index(op.f('ix_api_van_requests_request_id'), 'api_van_requests', ['requestId'], unique=True)
    op.create_unique_constraint(op.f('api_van_requests_request_id_key'), 'api_van_requests', ['requestId'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_api_user_profiles_userId'), table_name='api_user_profiles')
    op.create_index(op.f('ix_api_user_profiles_userId'), 'api_user_profiles', ['userId'], unique=False)
    op.create_unique_constraint(op.f('uq_api_user_profiles_userId'), 'api_user_profiles', ['userId'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_api_token_store_userId'), table_name='api_token_store')
    op.create_index(op.f('ix_api_token_store_user_id'), 'api_token_store', ['userId'], unique=False)
    op.drop_index(op.f('ix_api_mission_admin_panels_missionCode'), table_name='api_mission_admin_panels')
    op.create_index(op.f('ix_api_mission_admin_panels_mission_code'), 'api_mission_admin_panels', ['missionCode'], unique=False)
    op.create_unique_constraint(op.f('api_mission_admin_panels_mission_code_key'), 'api_mission_admin_panels', ['missionCode'], postgresql_nulls_not_distinct=False)
    op.alter_column('api_mission_admin_panels', 'missionTime',
               existing_type=sa.String(length=100),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.create_index(op.f('ix_api_audit_logs_createdAt'), 'api_audit_logs', ['createdAt'], unique=False)
    op.create_index(op.f('ix_api_audit_logs_action'), 'api_audit_logs', ['action'], unique=False)
    # ### end Alembic commands ###
